[build]
command = "python app.py"
publish = "."

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
PYTHON_VERSION = "3.8"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=31536000; includeSubDomains" 